### ISSUE TITLE
Duplicate key name 'state_scheduled' error

### ISSUE THREAD

**Issue by radmiraal** [Flowpack/jobqueue-doctrine#12]
We've always been running the `flow setup:queue <queue name>` command on all deploys to be sure the required queues for an application actually exist.

Since 3.0.2 this throws an exception about a duplicate key name 'state_scheduled'. Looking at the code the whole setUp() methods uses `IF NOT EXISTS` for table creation, but the index is always created.

I just tried using `CREATE INDEX IF NOT EXISTS...`  and that seems to fix the issue, but I can't find that in the mysql docs so I assume that's a mariadb feature (I'm at `10.3.14-MariaDB-1:10.3.14+maria~bionic`)

Before calling this a real bug: should it be safe to re-run the setup for a queue?

**Comment by markusguenther** [comment]
Thanks for reporting that @radmiraal ❤️
Seems that not many look into that repository :)

Need to test that.

**Comment by albe** [comment]
Regarding the create index: https://dba.stackexchange.com/questions/24531/mysql-create-index-if-not-exists

So this statement should be wrapped in try/catch. Generally, it should be safe to run the setup twice.
