### ISSUE TITLE
New release to take latest commits into account

### ISSUE THREAD

**Issue by DavidSporer** [Flowpack/jobqueue-doctrine#13]
Hi,

I think it would make sense to release a new version that contains the last five commits. With the latest Flow version (5.3.10) it's necessary to switch to dev-master since the doctrine ObjectManager has been removed in the meantime but is still imported in the DoctrineQueue.

Let me know if I can help with that.

Thanks,
David

**Comment by markusguenther** [comment]
Thanks for the hint @DavidSporer 
I released the latest changes so that it is now not necessary anymore to use master to be able to use that with flow 6.x.
