### ISSUE TITLE
incompatible with doctrine/persistence 1.3.*

### ISSUE THREAD

**Issue by fcool** [Flowpack/jobqueue-doctrine#16]
If doctrine/persistence 1.3.* gets installed, Flow breaks in compile time with:
Exception #1265213849 in line 359 of /home/fcool/PhpstormProjects/CouponGenerator2/Packages/Framework/Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php: The object "Doctrine\Persistence\ObjectManager" which was specified as a property in the object configuration of object "Flowpack\JobQueue\Doctrine\Queue\DoctrineQueue" (automatically registered class) does not exist. Check for spelling mistakes and if that dependency is correctly configured.

**Comment by markusguenther** [comment]
Can confirm that :/

**Comment by markusguenther** [comment]
Since version 1.3.0 the API has been changed and the autoloading was broken in the doctrine/persistence until version 1.3.3.

So when you have 1.3.6 (latest) it should work but for some reason flow did not use the right file.
Even when you change the use from ```use Doctrine\Common\Persistence\ObjectManager as DoctrineObjectManager;``` to ```use Doctrine\Persistence\ObjectManager as DoctrineObjectManager;```

it does not work. I personally downgraded back to 1.2

**Comment by markusguenther** [comment]
This has been mentioned already by @DavidSporer in https://github.com/Flowpack/jobqueue-doctrine/issues/13

**Comment by albe** [comment]
This should be fixed with https://github.com/neos/flow-development-collection/pull/1891
and also with version 3.0.3+ of this package: https://github.com/Flowpack/jobqueue-doctrine/releases/tag/3.0.3

can any of you confirm this?

**Comment by markusguenther** [comment]
Need to test it with the latest flow version. Yesterday it was not available and I released 3.0.3 :)

**Comment by sorenmalling** [comment]
@fcool 
I'm running Neos Flow 6.3 with the jobqueue - no issues in regard of compile time or usage.

Care to test again?

**Comment by albe** [comment]
Closing with above assessment. If there still is an issue, feel free to reopen :)
