### ISSUE TITLE
Poll interval is "0"

### ISSUE THREAD

**Issue by robertlemke** [Flowpack/jobqueue-doctrine#31]
Using 3.3.0-beta.2, I observed that the calculated poll interval is 0 (!). Using the same configuration but version 3.3.0-beta.1, the poll interval is correct (in my case 500000).

This seems to be a regression introduced by the type refactoring (https://github.com/Flowpack/jobqueue-doctrine/compare/3.3.0-beta.1..3.3.0-beta.2).

**Comment by robertlemke** [comment]
https://github.com/Flowpack/jobqueue-doctrine/issues/31

**Comment by bwaidelich** [comment]
I could imagine, that this change in particular is the culprit:
![image](https://github.com/Flowpack/jobqueue-doctrine/assets/307571/e25b861c-aac8-4750-8033-dde1b29794f7)

But then again, both variants should behave the same (https://3v4l.org/GQLSa#v8.2.7)

**Comment by bwaidelich** [comment]
Ah, of course there _is_ a major difference: https://3v4l.org/tM15o#v8.2.7

**Comment by kdambekalns** [comment]
😱 Sorry for that!
